### ISSUE TITLE
TransactionExpiredBlockheightExceededError: Signature  has expired: block height exceeded.

### ISSUE THREAD

**Issue by wgou** [Rico31415926/Solana-Metadata-token#1]
链接主网出现 TransactionExpiredBlockheightExceededError: Signature xxxxxxxxxxx has expired: block height exceeded.  错误。

调试发现 当前区块高度 与 最后有效区块高度 存在较大差值，web3js中采用轮询currentBlockHeight 和 lastValidBlockHeight，直到 currentBlockHeight >= lastValidBlockHeight .

调用路劲：
sendAndConfirm->builder.confirm->context.rpc.confirmTransaction ->confirmTransactionUsingBlockHeightExceedanceStrategy

可当满足之后，任然会出现这个错误。 节点能获取到这两个高度； 比较奇怪 是什么问题导致的。不知道作者在主网是否遇到此问题。

![微信图片_20240317025437](https://github.com/Rico31415926/Solana-Metadata-token/assets/5707747/412d168d-7acd-4ed8-b477-8d5db5aa9063)

**Comment by Rico31415926** [comment]
您可以更换个主网节点试试



在 2024-03-17 03:04:53，"wgou" ***@***.***> 写道：

链接主网出现 TransactionExpiredBlockheightExceededError: Signature xxxxxxxxxxx has expired: block height exceeded. 错误。

调试发现 当前区块高度 与 最后有效区块高度 存在较大差值，web3js中采用轮询currentBlockHeight 和 lastValidBlockHeight，直到 currentBlockHeight >= lastValidBlockHeight .

调用路劲：
sendAndConfirm->builder.confirm->context.rpc.confirmTransaction ->confirmTransactionUsingBlockHeightExceedanceStrategy

可当满足之后，任然会出现这个错误。 节点能获取到这两个高度； 比较奇怪 是什么问题导致的。不知道作者在主网是否遇到此问题。

_20240317025437.png (view on web)

**Comment by Rico31415926** [comment]
第一，您可以尝试更换主网节点
第二，您在tx交易之前，加上这一段代码
